[package]
name = "cn-guided-str-genotying"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noodles = { version = "*", features = ["bed"] }
rayon = "*"
rust-htslib = "*"
