[package]
name = "constrain"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ConSTRain"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
csv = "1.3.0"
ndarray = "0.15.6"
rayon = "*"
rust-htslib = { version = "*", default-features = false, features = ["bzip2", "lzma"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "*"
